title: Bioinfo:RAdelaide
description: Blog & lab info for Bioinformatics in Adelaide

url: https://jimmybgammyknee.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: CV
   url: /cv
 - title: Contact
   url: /contact

social:
   github: jimmybgammyknee
   twitter: wessidepraxis
   email: jimmymbreen@gmail.com

plugins:
  - jekyll-openmoji