title: Bioinformatics, BBQ & Beers
description: Personal blog & projects primarily based on Bioinformatics and data science

url: https://jimmybgammyknee.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: CV
   url: /cv
 - title: Contact
   url: /contact

social:
   github: jimmybgammyknee
   twitter: wessidepraxis
   email: jimmymbreen@gmail.com


